# Generated by Django 4.1.1 on 2022-09-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_delete_posts"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="author", new_name="user",),
    ]
